#############################
## NetData Monitoring Tool ##
#############################
version: '3.5'
services:
  netdata:
    container_name: netdata
    image: netdata/netdata
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
    environment:
      - PRETTY_NAME=Netdata Monitor
      - VIRTUAL_PORT=${P_NETDATA}
      - VIRTUAL_HOST=${SD_NETDATA}.${SERVER_DOMAIN}
      - LETSENCRYPT_HOST=${SD_NETDATA}.${SERVER_DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - reverse-proxy
    restart: unless-stopped

networks:
  reverse-proxy:
    external:
      name: reverse-proxy

