#########################
## Transmission Server ##
#########################
version: '3.5'
services:
  transmission:
    container_name: transmission
    image: linuxserver/transmission
    ports:
      - ${P_TRANSMISSION}:9091
      - 51413:51413
      - 51413:51413/udp
    depends_on:
      - nginx
      - letsencrypt
    volumes:
      - ${VOLUMES_PATH}/transmission/volumes/config:/config
      - ${STORAGE_PATH}/transmission/downloads:/downloads
      - ${STORAGE_PATH}/transmission/watch:/watch
    environment:
      - PRETTY_NAME=Transmission
      #- TRANSMISSION_WEB_HOME=/combustion-release
      - VIRTUAL_PORT=${P_TRANSMISSION}
      - VIRTUAL_HOST=${SD_TRANSMISSION}.${SERVER_DOMAIN}
      - LETSENCRYPT_HOST=${SD_TRANSMISSION}.${SERVER_DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - reverse-proxy
    restart: unless-stopped

networks:
  reverse-proxy:
    external:
      name: reverse-proxy

